version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    environment:
      - TESTING=true
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - JWT_SECRET=test-secret
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=qdrant-test
      - QDRANT_PORT=6333
      - NEO4J_URI=bolt://neo4j-test:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testpassword
    volumes:
      - ./test_output:/app/test_output
      - ./htmlcov:/app/htmlcov
      - ./coverage.xml:/app/coverage.xml
    depends_on:
      - qdrant-test
      - neo4j-test
    networks:
      - test-network

  qdrant-test:
    image: qdrant/qdrant:latest
    ports:
      - "6334:6333"
    volumes:
      - qdrant_test_data:/qdrant/storage
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  neo4j-test:
    image: neo4j:4.4
    environment:
      - NEO4J_AUTH=neo4j/testpassword
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=512M
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - neo4j_test_data:/data
      - neo4j_test_logs:/logs
      - neo4j_test_conf:/conf
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  qdrant_test_data:
    driver: local
  neo4j_test_data:
    driver: local
  neo4j_test_logs:
    driver: local
  neo4j_test_conf:
    driver: local

networks:
  test-network:
    driver: bridge
