version: '3.8'

services:
  neo4j:
    image: neo4j:5.15.0
    environment:
      - NEO4J_AUTH=neo4j/mombot123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=512m
    ports:
      - "7475:7474"  # Map to different external port
      - "7688:7687"  # Map to different external port
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - neo4j_test_data:/data
      - neo4j_test_logs:/logs

  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    environment:
      - NEO4J_URL=neo4j://neo4j:7687  # Internal port remains the same
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=mombot123
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TEST_USER_ID=alice123
      - PYTHONUNBUFFERED=1  # Enable real-time Python output
    volumes:
      - ./test_output:/app/test_output
    depends_on:
      neo4j:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for Neo4j to be ready...' &&
        sleep 10 &&
        echo 'Starting tests...' &&
        python test_graph_memory.py
      "

volumes:
  neo4j_test_data:
    name: neo4j_test_data_${TEST_RUN_ID:-default}
  neo4j_test_logs:
    name: neo4j_test_logs_${TEST_RUN_ID:-default}
